coin:
  min_withdraw: 1
  min_confirmations: 3
  min_tip: 1
  short_name: NIM
  full_name: Nimiq
  inv_precision: 100000
  miner_fee: 0.00140
  address_pattern: "\\S{4}[ _\\-\\+]?\\S{4}[ _\\-\\+]?\\S{4}[ _\\-\\+]?\\S{4}[ _\\-\\+]?\\S{4}[ _\\-\\+]?\\S{4}[ _\\-\\+]?\\S{4}[ _\\-\\+]?\\S{4}[ _\\-\\+]?\\S{4}"
  random_suffix: "\u1F916"
  random_length: 3
